FROM golang:alpine as build
RUN mkdir /app
WORKDIR /app
COPY ./hello .

RUN go build -a -gcflags=all="-l -B" -ldflags="-w -s"
RUN stat -c %s hello

FROM scratch
COPY --from=build /app/hello /
WORKDIR /

CMD ["./hello"]